begin;

create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;

select plan(123);

-- Shape, constraints, RLS, function traits, and least grants.
select has_table('public', 'items', 'item table exists');
select ok(
  pg_catalog.to_regclass('public.items_pkey') is not null,
  'item primary-key relation exists at the guarded name'
);
select ok(
  pg_catalog.to_regclass('public.items_public_id_unique') is not null,
  'public-ID unique relation exists at the guarded name'
);
select ok(
  pg_catalog.to_regclass('public.items_property_creation_request_unique') is not null,
  'request unique relation exists at the guarded name'
);
select is(
  pg_catalog.to_regclass('public.idx_items_property_id'),
  null::regclass,
  'property lookup reuses the compound unique index without a duplicate index'
);
select is(
  pg_catalog.to_regclass('public.idx_items_public_id'),
  null::regclass,
  'public-ID uniqueness has no redundant second index'
);
select has_function(
  'public',
  'create_current_item',
  array['uuid', 'uuid', 'text'],
  'item creation RPC accepts property hint, retry identity, and name only'
);
select has_function(
  'public',
  'read_public_item',
  array['uuid'],
  'public item reader accepts only the stable public identity'
);
select columns_are(
  'public',
  'items',
  array[
    'id',
    'public_id',
    'property_id',
    'creation_request_id',
    'name',
    'description',
    'published_at',
    'created_at',
    'updated_at'
  ],
  'isolated item table contains only the Slice 2C.1 boundary'
);
select col_type_is('public', 'items', 'id', 'uuid', 'internal item ID is uuid');
select col_type_is('public', 'items', 'public_id', 'uuid', 'public item ID is uuid');
select col_type_is('public', 'items', 'property_id', 'uuid', 'property parent is uuid');
select col_type_is(
  'public',
  'items',
  'creation_request_id',
  'uuid',
  'creation retry identity is uuid'
);
select col_type_is(
  'public',
  'items',
  'name',
  'character varying(120)',
  'item name has the 120-character storage bound'
);
select col_type_is('public', 'items', 'description', 'text', 'description is text');
select col_type_is(
  'public',
  'items',
  'published_at',
  'timestamp with time zone',
  'publication marker is timestamptz'
);
select col_type_is(
  'public',
  'items',
  'created_at',
  'timestamp with time zone',
  'creation timestamp is timestamptz'
);
select col_type_is(
  'public',
  'items',
  'updated_at',
  'timestamp with time zone',
  'update timestamp is timestamptz'
);
select col_is_null('public', 'items', 'description', 'description remains nullable compatibility data');
select col_is_null('public', 'items', 'published_at', 'publication marker is nullable');
select col_not_null('public', 'items', 'id', 'internal item ID is required');
select col_hasnt_default(
  'public',
  'items',
  'published_at',
  'draft items never publish by default'
);
select col_not_null('public', 'items', 'public_id', 'public identity is required');
select col_not_null('public', 'items', 'property_id', 'property parent is required');
select col_not_null(
  'public',
  'items',
  'creation_request_id',
  'creation retry identity is required'
);
select col_not_null('public', 'items', 'name', 'item name is required');
select col_not_null('public', 'items', 'created_at', 'creation timestamp is required');
select col_not_null('public', 'items', 'updated_at', 'update timestamp is required');
select col_default_is(
  'public',
  'items',
  'id',
  'gen_random_uuid()',
  'internal item ID is generated by the server'
);
select col_default_is(
  'public',
  'items',
  'public_id',
  'gen_random_uuid()',
  'public item ID is generated by the server'
);
select col_hasnt_default(
  'public',
  'items',
  'property_id',
  'property hint has no storage default'
);
select col_hasnt_default(
  'public',
  'items',
  'creation_request_id',
  'creation request has no storage default'
);
select col_hasnt_default('public', 'items', 'name', 'item name has no storage default');
select col_hasnt_default(
  'public',
  'items',
  'description',
  'compatibility description has no storage default'
);
select col_default_is(
  'public',
  'items',
  'created_at',
  'now()',
  'creation timestamp is set by the server'
);
select col_default_is(
  'public',
  'items',
  'updated_at',
  'now()',
  'initial update timestamp is set by the server'
);
select col_is_pk('public', 'items', 'id', 'internal item ID is the primary key');
select col_is_unique('public', 'items', 'public_id', 'public identity is globally unique');
select fk_ok(
  'public',
  'items',
  'property_id',
  'public',
  'properties',
  'id',
  'item property foreign key is present'
);
select ok(
  exists (
    select 1
    from pg_constraint as key_constraint
    where key_constraint.conrelid = 'public.items'::regclass
      and key_constraint.conname = 'items_property_creation_request_unique'
      and key_constraint.contype = 'u'
  ),
  'property and creation request have a named unique constraint'
);
select results_eq(
  $$
    select array_agg(attribute.attname::text order by key.ordinality)
    from pg_catalog.pg_constraint as key_constraint
    cross join lateral pg_catalog.unnest(key_constraint.conkey)
      with ordinality as key(attnum, ordinality)
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = key_constraint.conrelid
      and attribute.attnum = key.attnum
    where key_constraint.conrelid = 'public.items'::regclass
      and key_constraint.conname = 'items_property_creation_request_unique'
  $$,
  $$values (array['property_id', 'creation_request_id']::text[])$$,
  'request uniqueness covers exactly property then request ID'
);
select ok(
  (
    select key_constraint.confdeltype = 'c'
    from pg_catalog.pg_constraint as key_constraint
    where key_constraint.conrelid = 'public.items'::regclass
      and key_constraint.conname = 'items_property_id_fkey'
  ),
  'item foreign key cascades a deliberately deleted property'
);
select trigger_is(
  'public',
  'items',
  'update_items_updated_at',
  'public',
  'update_updated_at_column',
  'item updates use the shared timestamp trigger'
);
select ok(
  (select relrowsecurity from pg_class where oid = 'public.items'::regclass),
  'items have RLS enabled'
);
select is(
  (
    select count(*)
    from pg_policy
    where polrelid = 'public.items'::regclass
      and polcmd = 'r'
  ),
  1::bigint,
  'items expose exactly one member-select policy'
);
select ok(
  (
    select pg_get_expr(polqual, polrelid)
      like '%current_user_is_property_member(property_id)%'
    from pg_policy
    where polrelid = 'public.items'::regclass
      and polcmd = 'r'
  ),
  'item select policy delegates to the property membership helper'
);
select is(
  (
    select count(*)
    from pg_policy
    where polrelid = 'public.items'::regclass
      and polcmd in ('a', 'w', 'd')
  ),
  0::bigint,
  'items have no direct client write policies'
);
select ok(
  has_table_privilege('authenticated', 'public.items', 'select'),
  'authenticated clients can select member-visible items'
);
select ok(
  not has_table_privilege('authenticated', 'public.items', 'insert'),
  'authenticated clients cannot insert items directly'
);
select ok(
  not has_table_privilege('authenticated', 'public.items', 'update'),
  'authenticated clients cannot update or publish items directly'
);
select ok(
  not has_table_privilege('authenticated', 'public.items', 'delete'),
  'authenticated clients cannot delete items directly'
);
select ok(
  not has_table_privilege('anon', 'public.items', 'select'),
  'anonymous clients have zero item table read rights'
);
select ok(
  not has_table_privilege('anon', 'public.items', 'insert'),
  'anonymous clients have zero item table write rights'
);
select ok(
  not has_table_privilege('public', 'public.items', 'select'),
  'PUBLIC has zero item table rights'
);
select ok(
  not has_table_privilege('anon', 'public.items', 'update'),
  'anonymous clients cannot update items'
);
select ok(
  not has_table_privilege('anon', 'public.items', 'delete'),
  'anonymous clients cannot delete items'
);
select ok(
  not has_table_privilege('public', 'public.items', 'insert'),
  'PUBLIC cannot insert items'
);
select ok(
  not has_table_privilege('public', 'public.items', 'update'),
  'PUBLIC cannot update items'
);
select ok(
  not has_table_privilege('public', 'public.items', 'delete'),
  'PUBLIC cannot delete items'
);
select ok(
  has_function_privilege(
    'authenticated',
    'public.create_current_item(uuid,uuid,text)',
    'execute'
  ),
  'authenticated clients can execute item creation'
);
select ok(
  not has_function_privilege(
    'anon',
    'public.create_current_item(uuid,uuid,text)',
    'execute'
  ),
  'anonymous clients cannot execute item creation'
);
select ok(
  not has_function_privilege(
    'public',
    'public.create_current_item(uuid,uuid,text)',
    'execute'
  ),
  'PUBLIC has no item creation execution privilege'
);
select ok(
  has_function_privilege('anon', 'public.read_public_item(uuid)', 'execute'),
  'anonymous clients can execute the allow-listed public reader'
);
select ok(
  has_function_privilege('authenticated', 'public.read_public_item(uuid)', 'execute'),
  'authenticated clients can execute the same public reader'
);
select ok(
  not has_function_privilege('public', 'public.read_public_item(uuid)', 'execute'),
  'PUBLIC has no implicit public-reader execution privilege'
);
select ok(
  has_function_privilege(
    'authenticated',
    'private.current_user_is_property_member(uuid)',
    'execute'
  ),
  'authenticated item policy can execute its membership helper'
);
select ok(
  not has_function_privilege(
    'anon',
    'private.current_user_is_property_member(uuid)',
    'execute'
  ),
  'anonymous clients cannot execute the item membership helper'
);
select ok(
  (
    select
      rpc.prosecdef
      and rpc.proowner = item.relowner
      and rpc.proconfig = array['search_path=pg_catalog']::text[]
    from pg_proc as rpc
    cross join pg_class as item
    where rpc.oid = 'public.create_current_item(uuid,uuid,text)'::regprocedure
      and item.oid = 'public.items'::regclass
  ),
  'creation RPC is a fixed-path security definer owned with its table'
);
select ok(
  (
    select
      rpc.prosecdef
      and rpc.proowner = item.relowner
      and rpc.proconfig = array['search_path=pg_catalog']::text[]
    from pg_proc as rpc
    cross join pg_class as item
    where rpc.oid = 'public.read_public_item(uuid)'::regprocedure
      and item.oid = 'public.items'::regclass
  ),
  'public reader is a fixed-path security definer owned with its table'
);
select ok(
  (
    select
      helper.prosecdef
      and helper.proowner = item.relowner
      and helper.proconfig = array['search_path=pg_catalog']::text[]
    from pg_proc as helper
    cross join pg_class as item
    where helper.oid = 'private.current_user_is_property_member(uuid)'::regprocedure
      and item.oid = 'public.items'::regclass
  ),
  'item membership helper is a fixed-path security definer owned with its table'
);
select ok(
  pg_get_functiondef('public.create_current_item(uuid,uuid,text)'::regprocedure)
    like '%on conflict on constraint items_property_creation_request_unique do nothing%',
  'creation function serializes concurrent retries on the named unique boundary'
);
select ok(
  pg_get_functiondef('public.create_current_item(uuid,uuid,text)'::regprocedure)
    like '%for update of membership%',
  'creation function locks the writable membership against role races'
);
select ok(
  pg_get_functiondef('public.read_public_item(uuid)'::regprocedure)
    not like '%EXECUTE%'
    and pg_get_functiondef('public.read_public_item(uuid)'::regprocedure)
      like '%published_at is not null%',
  'public reader uses static SQL and requires publication'
);
select is(
  (
    select count(*)
    from information_schema.parameters as parameter
    where parameter.specific_schema = 'public'
      and parameter.specific_name like 'create_current_item_%'
      and parameter.parameter_mode = 'IN'
  ),
  3::bigint,
  'creation RPC accepts no account, user, description, publication, or QR input'
);

-- The prerequisite guard is backed by observable baseline shape, key, RLS,
-- and function-trait assertions rather than object names alone.
select results_eq(
  $$
    select attribute.attname::text, attribute.atttypid::regtype::text, attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'auth.users'::regclass
      and attribute.attname in ('id', 'email_confirmed_at')
    order by attribute.attname
  $$,
  $$values
    ('email_confirmed_at'::text, 'timestamp with time zone'::text, false),
    ('id'::text, 'uuid'::text, true)
  $$,
  'guarded auth columns retain the required types and nullability'
);
select results_eq(
  $$
    select attribute.attname::text, attribute.atttypid::regtype::text, attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.properties'::regclass
      and attribute.attname in ('id', 'account_id')
    order by attribute.attname
  $$,
  $$values
    ('account_id'::text, 'uuid'::text, true),
    ('id'::text, 'uuid'::text, true)
  $$,
  'guarded property columns retain UUID types and non-null tenancy'
);
select results_eq(
  $$
    select
      attribute.attname::text,
      pg_catalog.format_type(attribute.atttypid, attribute.atttypmod),
      attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.account_users'::regclass
      and attribute.attname in ('account_id', 'user_id', 'role')
    order by attribute.attname
  $$,
  $$values
    ('account_id'::text, 'uuid'::text, true),
    ('role'::text, 'character varying(20)'::text, true),
    ('user_id'::text, 'uuid'::text, true)
  $$,
  'guarded membership columns retain key, role, and nullability shape'
);
select results_eq(
  $$
    select array_agg(attribute.attname::text order by key.ordinality)
    from pg_catalog.pg_constraint as key_constraint
    cross join lateral pg_catalog.unnest(key_constraint.conkey)
      with ordinality as key(attnum, ordinality)
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = key_constraint.conrelid
      and attribute.attnum = key.attnum
    where key_constraint.conrelid = 'public.account_users'::regclass
      and key_constraint.contype = 'p'
  $$,
  $$values (array['account_id', 'user_id']::text[])$$,
  'guarded membership primary key locks one exact user/account row'
);
select ok(
  (
    select key_constraint.confdeltype = 'c'
    from pg_catalog.pg_constraint as key_constraint
    where key_constraint.conrelid = 'public.properties'::regclass
      and key_constraint.confrelid = 'public.accounts'::regclass
      and key_constraint.contype = 'f'
      and key_constraint.conkey = array[
        (
          select attribute.attnum
          from pg_catalog.pg_attribute as attribute
          where attribute.attrelid = 'public.properties'::regclass
            and attribute.attname = 'account_id'
        )
      ]::smallint[]
  ),
  'guarded property account key retains cascade semantics'
);
select ok(
  (
    select property.relrowsecurity and membership.relrowsecurity
    from pg_catalog.pg_class as property
    cross join pg_catalog.pg_class as membership
    where property.oid = 'public.properties'::regclass
      and membership.oid = 'public.account_users'::regclass
  ),
  'guarded property and membership prerequisites retain RLS'
);
select ok(
  (
    select
      not trigger_function.prosecdef
      and trigger_function.prorettype = 'pg_catalog.trigger'::regtype
      and trigger_function.proconfig = array['search_path=pg_catalog']::text[]
    from pg_catalog.pg_proc as trigger_function
    where trigger_function.oid = 'public.update_updated_at_column()'::regprocedure
  ),
  'guarded timestamp helper remains fixed-path trigger code'
);
select ok(
  (
    select
      not text_helper.prosecdef
      and text_helper.prorettype = 'pg_catalog.bool'::regtype
      and text_helper.provolatile = 'i'
      and text_helper.proconfig = array['search_path=pg_catalog']::text[]
    from pg_catalog.pg_proc as text_helper
    where text_helper.oid = 'private.text_has_unsafe_control(text)'::regprocedure
  ),
  'guarded text helper remains immutable fixed-path boolean code'
);
select ok(
  (
    select bool_and(
      helper.prosecdef
      and helper.proconfig = array['search_path=pg_catalog']::text[]
    )
    from pg_catalog.pg_proc as helper
    where helper.oid in (
      'private.current_user_is_account_member(uuid)'::regprocedure,
      'private.current_user_can_write_account(uuid)'::regprocedure,
      'public.resolve_current_property(text,text,text)'::regprocedure
    )
  ),
  'guarded account/property helpers remain fixed-path security definers'
);

insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
)
values
  (
    '00000000-0000-0000-0000-000000000000',
    '11111111-1111-4111-8111-111111111111',
    'authenticated',
    'authenticated',
    'item-host-a@example.test',
    '',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '22222222-2222-4222-8222-222222222222',
    'authenticated',
    'authenticated',
    'item-host-b@example.test',
    '',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '33333333-3333-4333-8333-333333333333',
    'authenticated',
    'authenticated',
    'item-host-unconfirmed@example.test',
    '',
    null,
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  );

insert into public.users (id, email)
values
  ('11111111-1111-4111-8111-111111111111', 'item-host-a@example.test'),
  ('22222222-2222-4222-8222-222222222222', 'item-host-b@example.test'),
  ('33333333-3333-4333-8333-333333333333', 'item-host-unconfirmed@example.test');

insert into public.accounts (id, owner_id, name)
values
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '11111111-1111-4111-8111-111111111111',
    'Item account A'
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    '22222222-2222-4222-8222-222222222222',
    'Item account B'
  );

insert into public.account_users (account_id, user_id, role, joined_at)
values
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '11111111-1111-4111-8111-111111111111',
    'owner',
    now()
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    '22222222-2222-4222-8222-222222222222',
    'admin',
    now()
  );

insert into public.properties (
  id,
  user_id,
  property_type_id,
  nickname,
  account_id
)
values
  (
    'aaaaaaaa-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000107',
    'Property A',
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  ),
  (
    'bbbbbbbb-2222-4222-8222-222222222222',
    '22222222-2222-4222-8222-222222222222',
    '00000000-0000-4000-8000-000000000107',
    'Property B',
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
  );

-- Authentication, confirmation, and input validation happen before writes.
select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claim.role', 'anon', true);
set local role anon;
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    'Anonymous item'
  )$$,
  '42501',
  null,
  'anonymous item creation is denied by the grant boundary'
);
reset role;

select set_config('request.jwt.claim.sub', '33333333-3333-4333-8333-333333333333', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    'Unconfirmed item'
  )$$,
  '42501',
  'Confirmed email required',
  'unconfirmed identity cannot create an item'
);
reset role;

select set_config('request.jwt.claim.sub', '11111111-1111-4111-8111-111111111111', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select throws_ok(
  $$select * from public.create_current_item(
    null,
    '00000000-0000-4000-8000-000000000201',
    'No property'
  )$$,
  '22023',
  'Property is required',
  'null property hint is rejected'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    null,
    'No request'
  )$$,
  '22023',
  'Creation request is required',
  'null creation request is rejected'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    null
  )$$,
  '22023',
  'Item name is required',
  'null item name is rejected'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    '   '
  )$$,
  '22023',
  'Item name is required',
  'blank item name is rejected'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    repeat('n', 121)
  )$$,
  '22001',
  'Item name is too long',
  'overlong item name is rejected'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    E'Line\nbreak'
  )$$,
  '22023',
  'Item name contains unsupported characters',
  'ASCII control characters are rejected from item names'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    'Zero​width'
  )$$,
  '22023',
  'Item name contains unsupported characters',
  'Unicode zero-width controls are rejected from item names'
);
select is(
  (select count(*) from public.items),
  0::bigint,
  'failed input checks create no item'
);

-- Owner creation normalizes one name, returns only the server result, and
-- leaves the item unpublished with no description.
select results_eq(
  $$
    select property_id, name
    from public.create_current_item(
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000201',
      '  Front door  '
    )
  $$,
  $$values (
    'aaaaaaaa-1111-4111-8111-111111111111'::uuid,
    'Front door'::text
  )$$,
  'owner creates one normalized draft item for the hinted property'
);
select ok(
  (
    select public_id is not null and id is not null
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000201'
  ),
  'created item has separate non-null internal and public UUID fields'
);
select results_eq(
  $$
    select name::text, description, published_at
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000201'
  $$,
  $$values ('Front door'::text, null::text, null::timestamptz)$$,
  'creation stores no compatibility description and never auto-publishes'
);
select is(
  (select count(*) from public.items),
  1::bigint,
  'first creation adds exactly one row'
);
select is(
  (
    select public_id
    from public.create_current_item(
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000201',
      'Front door'
    )
  ),
  (
    select public_id
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000201'
  ),
  'same normalized retry returns the stable existing public identity'
);
select is(
  (select count(*) from public.items),
  1::bigint,
  'same retry does not duplicate the item'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000201',
    'Back door'
  )$$,
  '22023',
  'Creation request conflicts with another item',
  'same request with a different normalized payload fails closed'
);
select is(
  (select count(*) from public.items),
  1::bigint,
  'conflicting retry leaves the existing row unchanged'
);
select is(
  (
    select name::text
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000201'
  ),
  'Front door'::text,
  'conflicting retry never renames the existing item'
);
select throws_ok(
  $$insert into public.items (property_id, creation_request_id, name)
    values (
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000202',
      'Direct insert'
    )$$,
  '42501',
  null,
  'owner cannot bypass creation with a direct insert'
);
select throws_ok(
  $$update public.items set published_at = statement_timestamp()$$,
  '42501',
  null,
  'owner cannot publish with a direct update'
);
select throws_ok(
  $$delete from public.items$$,
  '42501',
  null,
  'owner cannot directly delete an item'
);
reset role;

update public.items
set public_id = 'aaaaaaaa-0000-4000-8000-000000000001'
where property_id = 'aaaaaaaa-1111-4111-8111-111111111111'
  and name = 'Front door';

select throws_ok(
  $$insert into public.items (property_id, creation_request_id, name)
    values (
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000202',
      ' Not normalized '
    )$$,
  '23514',
  null,
  'table constraint rejects an unnormalized item name'
);
select throws_ok(
  $$insert into public.items (property_id, creation_request_id, name)
    values (
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000202',
      'Unsafe‮name'
    )$$,
  '23514',
  null,
  'table constraint rejects unsafe Unicode item text'
);

-- Cross-account property hints never establish authority. Admin and member
-- roles can create, while a viewer can only read its account.
select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select is(
  (select count(*) from public.items),
  0::bigint,
  'identity B cannot read identity A item before membership'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000203',
    'Cross account'
  )$$,
  'P0002',
  'Writable property not found',
  'cross-account property hint cannot create an item'
);
select is(
  (
    select name
    from public.create_current_item(
      'bbbbbbbb-2222-4222-8222-222222222222',
      '00000000-0000-4000-8000-000000000203',
      'Admin item'
    )
  ),
  'Admin item'::text,
  'account admin can create an item'
);
reset role;

insert into public.account_users (account_id, user_id, role, joined_at)
values (
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  '22222222-2222-4222-8222-222222222222',
  'member',
  now()
);

select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select is(
  (select count(*) from public.items),
  2::bigint,
  'account member reads items across both joined accounts'
);
select is(
  (
    select name
    from public.create_current_item(
      'aaaaaaaa-1111-4111-8111-111111111111',
      '00000000-0000-4000-8000-000000000204',
      'Member item'
    )
  ),
  'Member item'::text,
  'account member can create an item for the joined property'
);
reset role;

update public.account_users
set role = 'viewer'
where account_id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  and user_id = '22222222-2222-4222-8222-222222222222';

select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select ok(
  exists (
    select 1
    from public.items
    where property_id = 'aaaaaaaa-1111-4111-8111-111111111111'
      and name = 'Member item'
  ),
  'viewer retains same-account item read access'
);
select throws_ok(
  $$select * from public.create_current_item(
    'aaaaaaaa-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000205',
    'Viewer item'
  )$$,
  'P0002',
  'Writable property not found',
  'viewer cannot create an item'
);
reset role;
select is(
  (
    select count(*)
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000205'
  ),
  0::bigint,
  'viewer failure leaves no item row'
);

-- A request UUID is scoped to its property, not trusted as global tenant
-- context, so the same retry identity may safely exist for another property.
select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select lives_ok(
  $$select * from public.create_current_item(
    'bbbbbbbb-2222-4222-8222-222222222222',
    '00000000-0000-4000-8000-000000000201',
    'Same request, other property'
  )$$,
  'same request UUID can identify an independent creation on another property'
);
reset role;
select is(
  (
    select count(*)
    from public.items
    where creation_request_id = '00000000-0000-4000-8000-000000000201'
  ),
  2::bigint,
  'property-scoped request uniqueness preserves two independent items'
);

-- Draft and unknown public identities are indistinguishable. Publication is
-- arranged only as owner-side test fixture because no Slice 2C.1 client path
-- may set published_at.
select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claim.role', 'anon', true);
set local role anon;
select is(
  (
    select count(*)
    from public.read_public_item(
      'aaaaaaaa-0000-4000-8000-000000000001'
    )
  ),
  0::bigint,
  'anonymous reader cannot see a known draft public ID'
);
select is(
  (
    select count(*)
    from public.read_public_item('99999999-9999-4999-8999-999999999999')
  ),
  0::bigint,
  'anonymous reader cannot distinguish an unknown public ID'
);
select throws_ok(
  $$select count(*) from public.items$$,
  '42501',
  null,
  'anonymous role cannot inspect item rows directly'
);
reset role;

update public.items
set published_at = statement_timestamp()
where public_id = 'aaaaaaaa-0000-4000-8000-000000000001';

select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claim.role', 'anon', true);
set local role anon;
select results_eq(
  $$
    select name
    from public.read_public_item(
      'aaaaaaaa-0000-4000-8000-000000000001'
    )
  $$,
  $$values ('Front door'::text)$$,
  'anonymous reader receives only a published item name'
);
select is(
  pg_get_function_result('public.read_public_item(uuid)'::regprocedure),
  'TABLE(public_id uuid, name text)',
  'public reader output contains exactly the allow-listed public fields'
);
reset role;

delete from public.account_users
where account_id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  and user_id = '22222222-2222-4222-8222-222222222222';

select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select results_eq(
  $$
    select public_id, name
    from public.read_public_item(
      'aaaaaaaa-0000-4000-8000-000000000001'
    )
  $$,
  $$values (
    'aaaaaaaa-0000-4000-8000-000000000001'::uuid,
    'Front door'::text
  )$$,
  'authenticated non-member receives the same guest-safe published projection'
);
reset role;

select * from finish();
rollback;
