begin;

create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;

select plan(132);

-- Exact table shape, defaults, keys, trigger, and nonredundant indexes.
select has_table('public', 'item_articles', 'instruction/article table exists');
select has_function(
  'private',
  'instruction_body_has_unsafe_control',
  array['text'],
  'body-specific safety helper exists'
);
select has_function(
  'private',
  'trim_instruction_text',
  array['text'],
  'Unicode whitespace trim boundary exists'
);
select has_function(
  'private',
  'current_user_is_item_member',
  array['uuid'],
  'article membership helper exists'
);
select columns_are(
  'public',
  'item_articles',
  array[
    'id',
    'item_id',
    'creation_request_id',
    'purpose',
    'title',
    'description',
    'display_order',
    'created_at',
    'updated_at'
  ],
  'instruction table contains only the Slice 3A.1 boundary'
);
select col_type_is('public', 'item_articles', 'id', 'uuid', 'article ID is uuid');
select col_type_is('public', 'item_articles', 'item_id', 'uuid', 'item parent is uuid');
select col_type_is(
  'public',
  'item_articles',
  'creation_request_id',
  'uuid',
  'creation retry identity is uuid'
);
select col_type_is(
  'public',
  'item_articles',
  'purpose',
  'character varying(40)',
  'purpose has the 40-character storage bound'
);
select col_type_is(
  'public',
  'item_articles',
  'title',
  'character varying(120)',
  'title has the 120-character storage bound'
);
select col_type_is('public', 'item_articles', 'description', 'text', 'body is text');
select col_type_is(
  'public',
  'item_articles',
  'display_order',
  'integer',
  'display order is integer'
);
select col_type_is(
  'public',
  'item_articles',
  'created_at',
  'timestamp with time zone',
  'creation timestamp is timestamptz'
);
select col_type_is(
  'public',
  'item_articles',
  'updated_at',
  'timestamp with time zone',
  'update timestamp is timestamptz'
);
select col_not_null('public', 'item_articles', 'id', 'article ID is required');
select col_not_null('public', 'item_articles', 'item_id', 'item parent is required');
select col_not_null(
  'public',
  'item_articles',
  'creation_request_id',
  'creation request is required'
);
select col_not_null('public', 'item_articles', 'purpose', 'purpose is required');
select col_not_null('public', 'item_articles', 'title', 'title is required');
select col_not_null('public', 'item_articles', 'description', 'body is required');
select col_not_null('public', 'item_articles', 'display_order', 'display order is required');
select col_not_null('public', 'item_articles', 'created_at', 'creation timestamp is required');
select col_not_null('public', 'item_articles', 'updated_at', 'update timestamp is required');
select col_default_is(
  'public',
  'item_articles',
  'id',
  'gen_random_uuid()',
  'article ID is generated by the server'
);
select col_hasnt_default(
  'public',
  'item_articles',
  'item_id',
  'item parent has no default'
);
select col_hasnt_default(
  'public',
  'item_articles',
  'creation_request_id',
  'creation request has no default'
);
select col_default_is(
  'public',
  'item_articles',
  'purpose',
  'instructions',
  'server defaults purpose to instructions'
);
select col_hasnt_default('public', 'item_articles', 'title', 'title has no default');
select col_hasnt_default('public', 'item_articles', 'description', 'body has no default');
select col_default_is(
  'public',
  'item_articles',
  'display_order',
  '0',
  'first instruction defaults to display order zero'
);
select col_default_is(
  'public',
  'item_articles',
  'created_at',
  'now()',
  'creation timestamp is server-owned'
);
select col_default_is(
  'public',
  'item_articles',
  'updated_at',
  'now()',
  'initial update timestamp is server-owned'
);
select col_is_pk('public', 'item_articles', 'id', 'article ID is the primary key');
select fk_ok(
  'public',
  'item_articles',
  'item_id',
  'public',
  'items',
  'id',
  'article item foreign key is present'
);
select ok(
  (
    select key_constraint.confdeltype = 'c'
    from pg_catalog.pg_constraint as key_constraint
    where key_constraint.conrelid = 'public.item_articles'::regclass
      and key_constraint.conname = 'item_articles_item_id_fkey'
  ),
  'deleting an item cascades its instructions'
);
select is(
  (
    select array_agg(attribute.attname::text order by key.ordinality)
    from pg_catalog.pg_constraint as key_constraint
    cross join lateral pg_catalog.unnest(key_constraint.conkey)
      with ordinality as key(attnum, ordinality)
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = key_constraint.conrelid
      and attribute.attnum = key.attnum
    where key_constraint.conrelid = 'public.item_articles'::regclass
      and key_constraint.conname = 'item_articles_item_creation_request_unique'
  ),
  array['item_id', 'creation_request_id']::text[],
  'request uniqueness covers exactly item then creation request'
);
select is(
  (
    select array_agg(attribute.attname::text order by key.ordinality)
    from pg_catalog.pg_constraint as key_constraint
    cross join lateral pg_catalog.unnest(key_constraint.conkey)
      with ordinality as key(attnum, ordinality)
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = key_constraint.conrelid
      and attribute.attnum = key.attnum
    where key_constraint.conrelid = 'public.item_articles'::regclass
      and key_constraint.conname = 'item_articles_item_display_order_unique'
  ),
  array['item_id', 'display_order']::text[],
  'display uniqueness covers exactly item then order'
);
select is(
  pg_catalog.to_regclass('public.idx_item_articles_item_id'),
  null::regclass,
  'compound unique indexes avoid a redundant item-only index'
);
select is(
  pg_catalog.to_regclass('public.idx_item_articles_item_order'),
  null::regclass,
  'display-order uniqueness has no redundant second index'
);
select is(
  pg_catalog.to_regclass('public.idx_item_articles_source_language'),
  null::regclass,
  'deferred source language has no index'
);
select trigger_is(
  'public',
  'item_articles',
  'update_item_articles_updated_at',
  'public',
  'update_updated_at_column',
  'article updates use the shared timestamp trigger'
);
select is(
  (
    select count(*)
    from pg_catalog.pg_constraint
    where conrelid = 'public.item_articles'::regclass
      and contype = 'c'
  ),
  6::bigint,
  'instruction table has exactly six content/order check constraints'
);

-- RLS, ownership, fixed search paths, and least grants.
select ok(
  (select relrowsecurity from pg_catalog.pg_class where oid = 'public.item_articles'::regclass),
  'instructions have RLS enabled'
);
select ok(
  not (select relforcerowsecurity from pg_catalog.pg_class where oid = 'public.item_articles'::regclass),
  'isolated instructions do not force RLS'
);
select is(
  (
    select count(*)
    from pg_catalog.pg_policy
    where polrelid = 'public.item_articles'::regclass
      and polcmd = 'r'
  ),
  1::bigint,
  'instructions expose exactly one authenticated member-select policy'
);
select is(
  (
    select count(*)
    from pg_catalog.pg_policy
    where polrelid = 'public.item_articles'::regclass
      and polcmd in ('a', 'w', 'd')
  ),
  0::bigint,
  'instructions have no direct client write policies'
);
select ok(
  (
    select pg_catalog.pg_get_expr(polqual, polrelid)
      like '%current_user_is_item_member(item_id)%'
    from pg_catalog.pg_policy
    where polrelid = 'public.item_articles'::regclass
      and polcmd = 'r'
  ),
  'instruction select policy delegates to the item membership helper'
);
select ok(
  has_table_privilege('authenticated', 'public.item_articles', 'select'),
  'authenticated members receive read-only table access'
);
select ok(
  not has_table_privilege('authenticated', 'public.item_articles', 'insert'),
  'authenticated clients cannot insert instructions directly'
);
select ok(
  not has_table_privilege('authenticated', 'public.item_articles', 'update'),
  'authenticated clients cannot update instructions directly'
);
select ok(
  not has_table_privilege('authenticated', 'public.item_articles', 'delete'),
  'authenticated clients cannot delete instructions directly'
);
select ok(
  not has_table_privilege('anon', 'public.item_articles', 'select'),
  'anonymous clients cannot read instruction rows'
);
select ok(
  not has_table_privilege('anon', 'public.item_articles', 'insert'),
  'anonymous clients cannot insert instruction rows'
);
select ok(
  not has_table_privilege('anon', 'public.item_articles', 'update'),
  'anonymous clients cannot update instruction rows'
);
select ok(
  not has_table_privilege('anon', 'public.item_articles', 'delete'),
  'anonymous clients cannot delete instruction rows'
);
select ok(
  not has_table_privilege('public', 'public.item_articles', 'select'),
  'PUBLIC cannot read instruction rows'
);
select ok(
  not has_table_privilege('public', 'public.item_articles', 'insert'),
  'PUBLIC cannot insert instruction rows'
);
select ok(
  not has_table_privilege('public', 'public.item_articles', 'update'),
  'PUBLIC cannot update instruction rows'
);
select ok(
  not has_table_privilege('public', 'public.item_articles', 'delete'),
  'PUBLIC cannot delete instruction rows'
);
select ok(
  has_function_privilege(
    'authenticated',
    'private.current_user_is_item_member(uuid)',
    'execute'
  ),
  'authenticated RLS can execute the item membership helper'
);
select ok(
  not has_function_privilege('anon', 'private.current_user_is_item_member(uuid)', 'execute'),
  'anonymous clients cannot execute the membership helper'
);
select ok(
  not has_function_privilege('public', 'private.current_user_is_item_member(uuid)', 'execute'),
  'PUBLIC cannot execute the membership helper'
);
select ok(
  not has_function_privilege(
    'authenticated',
    'private.instruction_body_has_unsafe_control(text)',
    'execute'
  ),
  'authenticated clients cannot execute the private body helper'
);
select ok(
  not has_function_privilege('anon', 'private.instruction_body_has_unsafe_control(text)', 'execute'),
  'anonymous clients cannot execute the private body helper'
);
select ok(
  not has_function_privilege('public', 'private.instruction_body_has_unsafe_control(text)', 'execute'),
  'PUBLIC cannot execute the private body helper'
);
select ok(
  not has_function_privilege('authenticated', 'private.trim_instruction_text(text)', 'execute'),
  'authenticated clients cannot execute the private trim helper'
);
select ok(
  not has_function_privilege('anon', 'private.trim_instruction_text(text)', 'execute'),
  'anonymous clients cannot execute the private trim helper'
);
select ok(
  not has_function_privilege('public', 'private.trim_instruction_text(text)', 'execute'),
  'PUBLIC cannot execute the private trim helper'
);
select ok(
  (
    select
      helper.prosecdef
      and helper.provolatile = 's'
      and helper.prorettype = 'pg_catalog.bool'::regtype
      and helper.proconfig = array['search_path=pg_catalog']::text[]
      and helper.proowner = article.relowner
    from pg_catalog.pg_proc as helper
    cross join pg_catalog.pg_class as article
    where helper.oid = 'private.current_user_is_item_member(uuid)'::regprocedure
      and article.oid = 'public.item_articles'::regclass
  ),
  'membership helper is a table-owned fixed-path stable security definer'
);
select ok(
  (
    select
      not helper.prosecdef
      and helper.provolatile = 'i'
      and helper.prorettype = 'pg_catalog.bool'::regtype
      and helper.proconfig = array['search_path=pg_catalog']::text[]
      and helper.proowner = article.relowner
    from pg_catalog.pg_proc as helper
    cross join pg_catalog.pg_class as article
    where helper.oid = 'private.instruction_body_has_unsafe_control(text)'::regprocedure
      and article.oid = 'public.item_articles'::regclass
  ),
  'body helper is a table-owned fixed-path immutable security invoker'
);
select ok(
  (
    select
      not helper.prosecdef
      and helper.provolatile = 'i'
      and helper.proisstrict
      and helper.prorettype = 'pg_catalog.text'::regtype
      and helper.proconfig = array['search_path=pg_catalog']::text[]
      and helper.proowner = article.relowner
    from pg_catalog.pg_proc as helper
    cross join pg_catalog.pg_class as article
    where helper.oid = 'private.trim_instruction_text(text)'::regprocedure
      and article.oid = 'public.item_articles'::regclass
  ),
  'trim helper is a table-owned fixed-path immutable strict security invoker'
);
select ok(
  pg_catalog.pg_get_functiondef(
    'private.current_user_is_item_member(uuid)'::regprocedure
  ) not like '%EXECUTE%'
  and pg_catalog.pg_get_functiondef(
    'private.current_user_is_item_member(uuid)'::regprocedure
  ) like '%membership.user_id = auth.uid()%'
  and pg_catalog.pg_get_functiondef(
    'private.current_user_is_item_member(uuid)'::regprocedure
  ) like '%property.account_id%',
  'membership helper uses static identity-to-account ownership SQL'
);

-- Observable prerequisites back the fail-fast migration guards.
select results_eq(
  $$
    select attribute.attname::text collate "C",
      pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) collate "C",
      attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.account_users'::regclass
      and attribute.attname in ('account_id', 'user_id', 'role')
    order by attribute.attname
  $$,
  $$values
    ('account_id'::text collate "C", 'uuid'::text collate "C", true),
    ('role'::text collate "C", 'character varying(20)'::text collate "C", true),
    ('user_id'::text collate "C", 'uuid'::text collate "C", true)
  $$,
  'guarded membership identity and role columns retain exact shape'
);
select results_eq(
  $$
    select attribute.attname::text collate "C",
      pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) collate "C",
      attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.properties'::regclass
      and attribute.attname in ('id', 'account_id')
    order by attribute.attname
  $$,
  $$values
    ('account_id'::text collate "C", 'uuid'::text collate "C", true),
    ('id'::text collate "C", 'uuid'::text collate "C", true)
  $$,
  'guarded property identity and tenant columns retain exact shape'
);
select results_eq(
  $$
    select attribute.attname::text collate "C",
      pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) collate "C",
      attribute.attnotnull
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.items'::regclass
      and attribute.attname in ('id', 'property_id', 'public_id', 'published_at')
    order by attribute.attname
  $$,
  $$values
    ('id'::text collate "C", 'uuid'::text collate "C", true),
    ('property_id'::text collate "C", 'uuid'::text collate "C", true),
    ('public_id'::text collate "C", 'uuid'::text collate "C", true),
    ('published_at'::text collate "C", 'timestamp with time zone'::text collate "C", false)
  $$,
  'guarded item identity, parent, and draft columns retain exact shape'
);
select ok(
  (
    select membership.relrowsecurity
      and property.relrowsecurity
      and item.relrowsecurity
    from pg_catalog.pg_class as membership
    cross join pg_catalog.pg_class as property
    cross join pg_catalog.pg_class as item
    where membership.oid = 'public.account_users'::regclass
      and property.oid = 'public.properties'::regclass
      and item.oid = 'public.items'::regclass
  ),
  'guarded membership, property, and item tables retain RLS'
);
select ok(
  (
    select pg_catalog.bool_and(
      helper.proconfig = array['search_path=pg_catalog']::text[]
    )
    from pg_catalog.pg_proc as helper
    where helper.oid in (
      'public.update_updated_at_column()'::regprocedure,
      'private.text_has_unsafe_control(text)'::regprocedure,
      'private.current_user_is_account_member(uuid)'::regprocedure,
      'private.current_user_is_property_member(uuid)'::regprocedure,
      'public.create_current_item(uuid,uuid,text)'::regprocedure,
      'public.read_public_item(uuid)'::regprocedure
    )
  ),
  'guarded prerequisite helpers all retain fixed search paths'
);

-- The body helper permits formatting needed for instructions but nothing else.
select is(
  private.trim_instruction_text(
    pg_catalog.chr(9)
      || pg_catalog.chr(160)
      || pg_catalog.chr(5760)
      || pg_catalog.chr(8192)
      || 'Meaning'
      || pg_catalog.chr(12288)
      || pg_catalog.chr(8239)
      || pg_catalog.chr(13)
  ),
  'Meaning'::text,
  'trim helper removes ASCII and representative Unicode White_Space at both edges'
);
select is(
  private.trim_instruction_text(pg_catalog.chr(160) || pg_catalog.chr(12288)),
  ''::text,
  'Unicode whitespace-only text normalizes to blank'
);
select is(
  private.trim_instruction_text(E'First\n\tSecond'),
  E'First\n\tSecond'::text,
  'trim helper preserves meaningful internal line feed and tab'
);
select ok(
  not private.instruction_body_has_unsafe_control(E'First line\nSecond\tstep'),
  'instruction body permits line feed and horizontal tab'
);
select ok(
  not private.instruction_body_has_unsafe_control(null),
  'null helper input is safely treated as containing no forbidden character'
);
select ok(
  private.instruction_body_has_unsafe_control(E'carriage\rreturn'),
  'instruction body rejects other C0 controls'
);
select ok(
  private.instruction_body_has_unsafe_control(chr(127)),
  'instruction body rejects C1 controls'
);
select ok(
  private.instruction_body_has_unsafe_control('zero​width'),
  'instruction body rejects Unicode zero-width format controls'
);
select ok(
  private.instruction_body_has_unsafe_control('direction‮change'),
  'instruction body rejects Unicode direction controls'
);
select ok(
  private.instruction_body_has_unsafe_control('Arabic؀format'),
  'instruction body rejects Unicode Cf U+0600'
);
select ok(
  private.instruction_body_has_unsafe_control('Mongolian᠎format'),
  'instruction body rejects Unicode Cf U+180E'
);
select ok(
  private.instruction_body_has_unsafe_control(
    'supplementary' || pg_catalog.chr(917505) || pg_catalog.chr(917536)
  ),
  'instruction body rejects supplementary-plane language and tag controls'
);
select ok(
  private.instruction_body_has_unsafe_control(
    'separator' || pg_catalog.chr(8232) || pg_catalog.chr(8233)
  ),
  'instruction body rejects Unicode line and paragraph separators'
);

-- Two accounts and two items prove same-account reads and cross-account denial.
insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
)
values
  (
    '00000000-0000-0000-0000-000000000000',
    '41111111-1111-4111-8111-111111111111',
    'authenticated',
    'authenticated',
    'instruction-host-a@example.test',
    '',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '42222222-2222-4222-8222-222222222222',
    'authenticated',
    'authenticated',
    'instruction-host-b@example.test',
    '',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '43333333-3333-4333-8333-333333333333',
    'authenticated',
    'authenticated',
    'instruction-viewer@example.test',
    '',
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(),
    now()
  );

insert into public.users (id, email)
values
  ('41111111-1111-4111-8111-111111111111', 'instruction-host-a@example.test'),
  ('42222222-2222-4222-8222-222222222222', 'instruction-host-b@example.test'),
  ('43333333-3333-4333-8333-333333333333', 'instruction-viewer@example.test');

insert into public.accounts (id, owner_id, name)
values
  (
    '4aaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '41111111-1111-4111-8111-111111111111',
    'Instruction account A'
  ),
  (
    '4bbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    '42222222-2222-4222-8222-222222222222',
    'Instruction account B'
  );

insert into public.account_users (account_id, user_id, role, joined_at)
values
  (
    '4aaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '41111111-1111-4111-8111-111111111111',
    'owner',
    now()
  ),
  (
    '4bbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    '42222222-2222-4222-8222-222222222222',
    'owner',
    now()
  ),
  (
    '4aaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '43333333-3333-4333-8333-333333333333',
    'viewer',
    now()
  );

insert into public.properties (
  id,
  user_id,
  property_type_id,
  nickname,
  account_id
)
values
  (
    '4aaaaaaa-1111-4111-8111-111111111111',
    '41111111-1111-4111-8111-111111111111',
    '00000000-0000-4000-8000-000000000107',
    'Instruction property A',
    '4aaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  ),
  (
    '4bbbbbbb-2222-4222-8222-222222222222',
    '42222222-2222-4222-8222-222222222222',
    '00000000-0000-4000-8000-000000000107',
    'Instruction property B',
    '4bbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
  );

insert into public.items (
  id,
  public_id,
  property_id,
  creation_request_id,
  name
)
values
  (
    '4aaaaaaa-0000-4000-8000-000000000001',
    '4aaaaaaa-0000-4000-8000-000000000002',
    '4aaaaaaa-1111-4111-8111-111111111111',
    '4aaaaaaa-0000-4000-8000-000000000003',
    'Coffee machine A'
  ),
  (
    '4bbbbbbb-0000-4000-8000-000000000001',
    '4bbbbbbb-0000-4000-8000-000000000002',
    '4bbbbbbb-2222-4222-8222-222222222222',
    '4bbbbbbb-0000-4000-8000-000000000003',
    'Coffee machine B'
  );

insert into public.item_articles (
  id,
  item_id,
  creation_request_id,
  title,
  description
)
values
  (
    '4aaaaaaa-1000-4000-8000-000000000001',
    '4aaaaaaa-0000-4000-8000-000000000001',
    '4aaaaaaa-1000-4000-8000-000000000002',
    'Make coffee',
    E'Fill the tank.\nPress the large button.\tWait.'
  ),
  (
    '4bbbbbbb-1000-4000-8000-000000000001',
    '4bbbbbbb-0000-4000-8000-000000000001',
    '4bbbbbbb-1000-4000-8000-000000000002',
    'Make coffee',
    'Press start.'
  );

select results_eq(
  $$
    select purpose::text, display_order, description
    from public.item_articles
    where id = '4aaaaaaa-1000-4000-8000-000000000001'
  $$,
  $$values (
    'instructions'::text,
    0,
    E'Fill the tank.\nPress the large button.\tWait.'::text
  )$$,
  'server defaults and permitted body formatting are stored exactly'
);
select ok(
  (
    select id is not null and created_at is not null and updated_at is not null
    from public.item_articles
    where id = '4aaaaaaa-1000-4000-8000-000000000001'
  ),
  'article identity and timestamps are non-null'
);

select set_config('request.jwt.claim.sub', '41111111-1111-4111-8111-111111111111', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select results_eq(
  $$select title::text from public.item_articles order by title$$,
  $$values ('Make coffee'::text)$$,
  'account A member reads only account A instructions'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000003',
      'Direct insert',
      'Forbidden'
    )$$,
  '42501',
  null,
  'authenticated owner cannot insert instructions directly'
);
select throws_ok(
  $$update public.item_articles set title = 'Direct update'$$,
  '42501',
  null,
  'authenticated owner cannot update instructions directly'
);
select throws_ok(
  $$delete from public.item_articles$$,
  '42501',
  null,
  'authenticated owner cannot delete instructions directly'
);
reset role;

select set_config('request.jwt.claim.sub', '42222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select results_eq(
  $$select id from public.item_articles$$,
  $$values ('4bbbbbbb-1000-4000-8000-000000000001'::uuid)$$,
  'account B cannot read account A instructions'
);
reset role;

select set_config('request.jwt.claim.sub', '43333333-3333-4333-8333-333333333333', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select ok(
  exists (
    select 1
    from public.item_articles
    where id = '4aaaaaaa-1000-4000-8000-000000000001'
  ),
  'same-account viewer can select an instruction'
);
select is(
  (
    select count(*)
    from public.item_articles
    where id = '4bbbbbbb-1000-4000-8000-000000000001'
  ),
  0::bigint,
  'viewer cannot select a cross-account instruction'
);
reset role;

select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claim.role', 'anon', true);
set local role anon;
select throws_ok(
  $$select count(*) from public.item_articles$$,
  '42501',
  null,
  'anonymous guest cannot inspect instruction storage'
);
reset role;

-- Storage constraints remain authoritative even for table-owner fixtures.
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000010',
      ' Wrong title ',
      'Valid body'
    )$$,
  '23514',
  null,
  'unnormalized title is rejected'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000011',
      E'Unsafe\ntitle',
      'Valid body'
    )$$,
  '23514',
  null,
  'title rejects line breaks through the strict shared helper'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000012',
      'Unsafe title‮',
      'Valid body'
    )$$,
  '23514',
  null,
  'title rejects Unicode format controls'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000029',
      'Arabic؀format',
      'Valid body'
    )$$,
  '23514',
  null,
  'title rejects Unicode Cf outside the inherited partial helper set'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000030',
      pg_catalog.chr(160),
      'Valid body'
    )$$,
  '23514',
  null,
  'NBSP-only title is rejected as blank'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000031',
      pg_catalog.chr(160) || 'Title',
      'Valid body'
    )$$,
  '23514',
  null,
  'outer NBSP title must be normalized before storage'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000022',
      repeat('t', 121),
      'Valid body'
    )$$,
  '22001',
  null,
  'title over 120 characters is rejected'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000013',
      'Blank body',
      '   '
    )$$,
  '23514',
  null,
  'blank body is rejected'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000023',
      'Whitespace body',
      E'\n\t\n'
    )$$,
  '23514',
  null,
  'line-feed and tab-only body is rejected as blank'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000032',
      'Unicode blank body',
      pg_catalog.chr(160)
    )$$,
  '23514',
  null,
  'NBSP-only body is rejected as blank'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000033',
      'Unicode outer whitespace',
      pg_catalog.chr(160) || 'Meaningful body'
    )$$,
  '23514',
  null,
  'outer NBSP body must be normalized before storage'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000024',
      'Outer whitespace',
      E'\nMeaningful body\t'
    )$$,
  '23514',
  null,
  'outer permitted body whitespace must be normalized before storage'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000014',
      'Unnormalized body',
      ' padded body '
    )$$,
  '23514',
  null,
  'unnormalized body is rejected'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000015',
      'Long body',
      repeat('b', 8001)
    )$$,
  '23514',
  null,
  'body over 8000 characters is rejected'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000016',
      'Unsafe body',
      E'carriage\rreturn'
    )$$,
  '23514',
  null,
  'body rejects disallowed C0 controls'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000017',
      'Unsafe body',
      'zero​width'
    )$$,
  '23514',
  null,
  'body rejects Unicode format controls'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000034',
      'Complete format set',
      'Body' || pg_catalog.chr(1536) || pg_catalog.chr(6158)
        || pg_catalog.chr(917505) || pg_catalog.chr(917536)
    )$$,
  '23514',
  null,
  'body table constraint rejects BMP and supplementary Unicode Cf controls'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000035',
      'Format separators',
      'Body' || pg_catalog.chr(8232) || pg_catalog.chr(8233)
    )$$,
  '23514',
  null,
  'body table constraint rejects Unicode line and paragraph separators'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      purpose,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000018',
      'faq',
      'Wrong purpose',
      'Valid body',
      1
    )$$,
  '23514',
  null,
  'purpose is constrained exactly to instructions'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      purpose,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000027',
      null,
      'Null purpose',
      'Valid body',
      1
    )$$,
  '23502',
  null,
  'purpose cannot be null'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000028',
      'Null body',
      null
    )$$,
  '23502',
  null,
  'instruction body cannot be null'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000019',
      'Negative order',
      'Valid body',
      -1
    )$$,
  '23514',
  null,
  'negative display order is rejected'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000025',
      'Null order',
      'Valid body',
      null
    )$$,
  '23502',
  null,
  'null display order is rejected'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000020',
      'Duplicate order',
      'Valid body',
      0
    )$$,
  '23505',
  null,
  'display order is unique within an item'
);
select throws_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000002',
      'Duplicate request',
      'Valid body',
      1
    )$$,
  '23505',
  null,
  'creation request is unique within an item'
);
select throws_ok(
  $$insert into public.item_articles (item_id, creation_request_id, title, description)
    values (
      '49999999-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000026',
      'Missing item',
      'Valid body'
    )$$,
  '23503',
  null,
  'article requires an existing item parent'
);
select lives_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4bbbbbbb-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000002',
      'Same request other item',
      'Valid body',
      1
    )$$,
  'the same request UUID is independent for another item'
);
select lives_ok(
  $$insert into public.item_articles (
      item_id,
      creation_request_id,
      title,
      description,
      display_order
    ) values (
      '4aaaaaaa-0000-4000-8000-000000000001',
      '4aaaaaaa-1000-4000-8000-000000000021',
      'Second step',
      E'Line one\n\tLine two',
      1
    )$$,
  'valid second instruction stores with newline and tab'
);
select is(
  (
    select count(*)
    from public.item_articles
    where item_id = '4aaaaaaa-0000-4000-8000-000000000001'
  ),
  2::bigint,
  'one item can hold two ordered instructions'
);
select lives_ok(
  $$update public.item_articles
    set title = 'Second step revised'
    where id = '4aaaaaaa-1000-4000-8000-000000000001'$$,
  'table owner fixture can exercise the shared update trigger'
);
select ok(
  (
    select updated_at >= created_at
    from public.item_articles
    where id = '4aaaaaaa-1000-4000-8000-000000000001'
  ),
  'shared trigger keeps updated_at at or after created_at'
);

delete from public.items
where id = '4aaaaaaa-0000-4000-8000-000000000001';
select is(
  (
    select count(*)
    from public.item_articles
    where item_id = '4aaaaaaa-0000-4000-8000-000000000001'
  ),
  0::bigint,
  'deleting an item cascades all of its instructions'
);

select * from finish();
rollback;
