[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npx --yes npm@10.9.9 ci --include=optional"]

[phases.build]
cmds = ["npx --yes npm@10.9.9 run build"]

[start]
cmd = "npm start"
