/**
 * E2E Test Module Exports
 *
 * Barrel export file for all E2E test utilities and helpers.
 *
 * @module ItemCreationWorkflow/__tests__/e2e
 * @lastModified 2026-01-10 (REQ-172 E2E Flow Testing)
 */

// Test utilities and helpers
export {
  // Constants
  NEW_WORKFLOW_STEPS_ORDER,
  NEW_STEP_DISPLAY_LABELS,
  PURPOSE_TYPE_LABELS,
  CONTENT_OPTION_LABELS,

  // Render utilities
  renderWorkflowForE2E,

  // Wait utilities
  waitForStep,
  waitForPurposeStep,
  waitForContentPreview,
  waitForPreviewSaveStep,

  // Basic navigation
  clickContinue,
  clickBack,
  selectRoom,
  selectItemType,
  selectSpecificItem,
  selectPurpose,
  selectContentOption,

  // Path navigation helpers
  navigateToPurposeStep,
  navigateToContentTypeStep,
  navigateToContentCreation,
  navigateToPreviewSaveStep,
  navigateToNextActionStep,
  navigateToSessionSummary,

  // Mock utilities
  createMockFile,
  createMockFileUpload,

  // Assertion helpers
  assertAutoGeneratedTitle,
  assertCurrentStep,
  assertPurposeInPreview,
  assertFieldsReadOnly,
  assertContentCount,

  // Test data generators
  generateFlowTestCases,
  generatePurposeTestCases,

  // Types
  type E2ERenderResult,
  type NavigationOptions,
} from './test-utils';
