'use client';

/**
 * Component Test Index Page
 *
 * Central hub for all pipeline and component test harnesses.
 * Auto-generated by pipeline orchestrator.
 *
 * @route /test
 * @generated 2026-01-10 11:36
 */

import Link from 'next/link';

interface TestLink {
  href: string;
  title: string;
  description: string;
}

const pipelineTests: TestLink[] = [
  {
    href: '/test/item-creation-workflow',
    title: 'Item Creation Workflow',
    description: 'Test harness for item-creation-workflow pipeline',
  },
  {
    href: '/test/simple-dashboard',
    title: 'Simple Dashboard',
    description: 'Test harness for simple-dashboard pipeline',
  },
  {
    href: '/test/ui-ux-workflow-improvements',
    title: 'Ui Ux Workflow Improvements',
    description: 'Test harness for ui-ux-workflow-improvements pipeline',
  },
];

const componentTests: TestLink[] = [
  {
    href: '/test/asset-dropzone',
    title: 'Asset Dropzone',
    description: 'Component test page',
  },
  {
    href: '/test/basic-shared-components',
    title: 'Basic Shared Components',
    description: 'Component test page',
  },
  {
    href: '/test/bundle-test',
    title: 'Bundle Test',
    description: 'Component test page',
  },
  {
    href: '/test/camera-preview',
    title: 'Camera Preview',
    description: 'Component test page',
  },
  {
    href: '/test/content-type-step',
    title: 'Content Type Step',
    description: 'Component test page',
  },
  {
    href: '/test/file-upload-step',
    title: 'File Upload Step',
    description: 'Component test page',
  },
  {
    href: '/test/image-cropper',
    title: 'Image Cropper',
    description: 'Component test page',
  },
  {
    href: '/test/image-rotator',
    title: 'Image Rotator',
    description: 'Component test page',
  },
  {
    href: '/test/inline-edit',
    title: 'Inline Edit',
    description: 'Component test page',
  },
  {
    href: '/test/instructions-viewer',
    title: 'Instructions Viewer',
    description: 'Component test page',
  },
  {
    href: '/test/item-capture',
    title: 'Item Capture',
    description: 'Component test page',
  },
  {
    href: '/test/item-manager',
    title: 'Item Manager',
    description: 'Component test page',
  },
  {
    href: '/test/item-preview-modal',
    title: 'Item Preview Modal',
    description: 'Component test page',
  },
  {
    href: '/test/markdown-editor',
    title: 'Markdown Editor',
    description: 'Component test page',
  },
  {
    href: '/test/media-editor-step',
    title: 'Media Editor Step',
    description: 'Component test page',
  },
  {
    href: '/test/media-thumbnail',
    title: 'Media Thumbnail',
    description: 'Component test page',
  },
  {
    href: '/test/metadata-step',
    title: 'Metadata Step',
    description: 'Component test page',
  },
  {
    href: '/test/photo-capture-step',
    title: 'Photo Capture Step',
    description: 'Component test page',
  },
  {
    href: '/test/print-options-panel',
    title: 'Print Options Panel',
    description: 'Component test page',
  },
  {
    href: '/test/review-step',
    title: 'Review Step',
    description: 'Component test page',
  },
  {
    href: '/test/text-editor-step',
    title: 'Text Editor Step',
    description: 'Component test page',
  },
  {
    href: '/test/video-capture-step',
    title: 'Video Capture Step',
    description: 'Component test page',
  },
  {
    href: '/test/video-trimmer',
    title: 'Video Trimmer',
    description: 'Component test page',
  },
];

function TestLinkCard({ href, title, description }: TestLink) {
  return (
    <Link
      href={href}
      className="block p-4 border border-gray-200 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition-colors"
    >
      <h3 className="font-semibold text-blue-600">{title}</h3>
      <p className="text-sm text-gray-600 mt-1">{description}</p>
    </Link>
  );
}

export default function TestIndexPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Test Harness Index</h1>
          <p className="text-gray-600 mt-2">
            Central hub for all pipeline and component test harnesses.
          </p>
          <p className="text-xs text-gray-400 mt-1">Last updated: 2026-01-10 11:36</p>
        </div>

        {/* Pipeline Test Harnesses */}
        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-4">🚀 Pipeline Test Harnesses</h2>
          {pipelineTests.length > 0 ? (
            <div className="grid gap-4">
              {pipelineTests.map((test) => (
                <TestLinkCard key={test.href} {...test} />
              ))}
            </div>
          ) : (
            <p className="text-gray-500">No pipeline test harnesses generated yet. Run testcheck stage to generate.</p>
          )}
        </section>

        {/* Component Tests */}
        {componentTests.length > 0 && (
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">🧩 Standalone Component Tests</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {componentTests.map((test) => (
                <TestLinkCard key={test.href} {...test} />
              ))}
            </div>
          </section>
        )}

        {/* Footer */}
        <footer className="text-center text-sm text-gray-500 py-4">
          Test Harness Index • Auto-generated by pipeline orchestrator
        </footer>
      </div>
    </div>
  );
}
